linters:
  enable:
    - whitespace
    - wastedassign
    - unconvert
    - tparallel
    - thelper
    - prealloc
    - predeclared
    - nolintlint
    - misspell
    - makezero
    - importas
    - ifshort
    - gosec
    - gofmt
    - goconst
    - forcetypeassert
    - dogsled
    - dupl
    - errname
    - errorlint

issues:
  exclude-rules:
    - path: "(.+)_test.go"
      linters:
        - dupl