name: Continuous Integration

on:
  push:
    paths:
      - "**.go"
      - "**.cue"
      - ".github/workflows/unit-test.yaml"
      - "go.mod"
      - "go.sum"
    branches:
      - main
  pull_request:
    paths:
      - "**.go"
      - "**.cue"
      - ".github/workflows/unit-test.yaml"
      - "go.mod"
      - "go.sum"
    branches:
      - main

env:
  DAGGER_LOG_FORMAT: plain

jobs:
  unit-tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Expose GitHub Runtime"
        uses: crazy-max/ghaction-github-runtime@v1

      - name: "Set up dagger"
        uses: dagger/dagger-for-github@v3
        with:
          install-only: true

      - name: Test
        run: dagger project update && dagger do test coverage

      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_SECRET }}
          files: /tmp/cov.txt
